#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# SPD Indonesia — One-shot VPS bootstrap (Ubuntu 24.04 LTS)
#
# Provisions a fresh Ubuntu 24.04 VPS for spdindonesia.org:
#   Node.js 20 LTS, PM2, Nginx, Certbot, clones repo, builds SPA,
#   installs backend deps, writes a placeholder backend/.env, starts
#   the API under PM2, wires Nginx, and prints next steps (DNS + TLS).
#
# Run as root (or with sudo) on a FRESH server:
#   curl -fsSL https://raw.githubusercontent.com/msyafiqwahyudi26/spd-website/main/deploy/setup-vps.sh | sudo bash
# or
#   sudo bash deploy/setup-vps.sh
#
# Safe to re-run: each step is idempotent where practical.
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Config ───────────────────────────────────────────────────────────
REPO_URL="https://github.com/msyafiqwahyudi26/spd-website.git"
APP_DIR="/var/www/spd-website"
BACKEND_DIR="${APP_DIR}/backend"
DOMAIN="spdindonesia.org"
WWW_DOMAIN="www.spdindonesia.org"
NGINX_SITE="/etc/nginx/sites-available/${DOMAIN}"
NGINX_LINK="/etc/nginx/sites-enabled/${DOMAIN}"
NODE_MAJOR=20

# ── Helpers ──────────────────────────────────────────────────────────
log()  { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[err]\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root: sudo bash $0"

export DEBIAN_FRONTEND=noninteractive

# ── 1. System update ─────────────────────────────────────────────────
log "Updating apt and upgrading system packages"
apt-get update -y
apt-get upgrade -y
apt-get install -y curl ca-certificates gnupg git ufw build-essential

# ── 2. Node.js 20 LTS (NodeSource) ───────────────────────────────────
if ! command -v node >/dev/null 2>&1 || \
   [[ "$(node -v 2>/dev/null | sed 's/v\([0-9]*\).*/\1/')" != "${NODE_MAJOR}" ]]; then
    log "Installing Node.js ${NODE_MAJOR} LTS via NodeSource"
    curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash -
    apt-get install -y nodejs
else
    log "Node.js $(node -v) already installed — skipping"
fi
log "node: $(node -v)   npm: $(npm -v)"

# ── 3. PM2 ───────────────────────────────────────────────────────────
if ! command -v pm2 >/dev/null 2>&1; then
    log "Installing PM2 globally"
    npm install -g pm2
else
    log "PM2 $(pm2 -v) already installed — skipping"
fi

# ── 4. Nginx ─────────────────────────────────────────────────────────
log "Installing Nginx"
apt-get install -y nginx
systemctl enable --now nginx

# ── 5. Certbot + Nginx plugin ────────────────────────────────────────
log "Installing Certbot (Let's Encrypt)"
apt-get install -y certbot python3-certbot-nginx

# ── 6. Firewall (optional but sensible) ──────────────────────────────
if command -v ufw >/dev/null 2>&1; then
    log "Configuring UFW (OpenSSH + Nginx Full)"
    ufw allow OpenSSH         >/dev/null 2>&1 || true
    ufw allow 'Nginx Full'    >/dev/null 2>&1 || true
    yes | ufw enable          >/dev/null 2>&1 || true
fi

# ── 7. Clone / update repo ───────────────────────────────────────────
if [[ -d "${APP_DIR}/.git" ]]; then
    log "Repo already present at ${APP_DIR} — pulling latest"
    git -C "${APP_DIR}" fetch --all --prune
    git -C "${APP_DIR}" reset --hard origin/main
else
    log "Cloning ${REPO_URL} into ${APP_DIR}"
    mkdir -p "$(dirname "${APP_DIR}")"
    git clone "${REPO_URL}" "${APP_DIR}"
fi

# ── 8. Frontend install + build ──────────────────────────────────────
log "Installing frontend deps and building Vite bundle"
cd "${APP_DIR}"
# B5: Use npm ci (not npm install) so prod matches package-lock.json exactly.
npm ci
# B3: Set VITE_API_URL so the bundle hits the same-origin /api proxy, not localhost.
VITE_API_URL=/api npm run build

# ── 9. Backend install (production only) ─────────────────────────────
log "Installing backend deps (production)"
cd "${BACKEND_DIR}"
# B5: npm ci for reproducible installs.
npm ci --omit=dev

# ── 10. Backend .env (placeholders — EDIT BEFORE GOING LIVE) ─────────
ENV_FILE="${BACKEND_DIR}/.env"
if [[ ! -f "${ENV_FILE}" ]]; then
    log "Writing placeholder ${ENV_FILE} — YOU MUST EDIT THIS"
    JWT_PLACEHOLDER="$(openssl rand -base64 48 | tr -d '\n')"
    cat > "${ENV_FILE}" <<EOF
# SPD Backend — production env
# Generated by deploy/setup-vps.sh on $(date -Is)
# Edit placeholders (CHANGE_ME) before restarting PM2.

NODE_ENV=production
PORT=5000

# Prisma schema currently declares provider="sqlite".
# Keep SQLite (simplest) OR switch schema.prisma to postgresql and
# point DATABASE_URL at a real Postgres instance.
DATABASE_URL="file:/var/www/spd-website/backend/prisma/prod.db"

# REQUIRED. Min 32 chars. Auto-generated below — keep or replace.
JWT_SECRET="${JWT_PLACEHOLDER}"

# Only origin allowed by CORS in production.
FRONTEND_URL=https://${DOMAIN}

# 1 proxy in front (Nginx). Set to 2 if you add Cloudflare later.
TRUST_PROXY=1

# SMTP — leave blank to disable email (contact form will no-op).
EMAIL_HOST=CHANGE_ME
EMAIL_PORT=587
EMAIL_USER=CHANGE_ME
EMAIL_PASS=CHANGE_ME
EMAIL_FROM=SPD Indonesia <no-reply@${DOMAIN}>
EMAIL_TO=admin@${DOMAIN}
EOF
    chmod 600 "${ENV_FILE}"
else
    log "${ENV_FILE} already exists — leaving untouched"
fi

# ── 11. Prisma client + DB init ──────────────────────────────────────
log "Generating Prisma client and pushing schema"
cd "${BACKEND_DIR}"
npx prisma generate
# B2: Removed --accept-data-loss — that flag can silently truncate tables on schema drift.
# db push without it is safe for additive changes (new columns/tables only).
npx prisma db push || warn "prisma db push failed — check DATABASE_URL and schema"

# Make sure uploads dir exists and is writable
mkdir -p "${BACKEND_DIR}/uploads" "${BACKEND_DIR}/logs"
chown -R www-data:www-data "${APP_DIR}/dist" "${BACKEND_DIR}/uploads" || true

# ── 12. PM2 start + persist ──────────────────────────────────────────
log "Starting backend under PM2"
cd "${BACKEND_DIR}"
pm2 delete spd-backend >/dev/null 2>&1 || true
pm2 start ecosystem.config.cjs
pm2 save

log "Wiring PM2 to systemd so it survives reboot"
# `pm2 startup` prints a command; running it with systemd executes the
# install step for the current (root) user.
pm2 startup systemd -u root --hp /root | tail -n 1 | bash || \
    warn "pm2 startup wiring failed — re-run 'pm2 startup' manually"

# ── 13. Nginx site ───────────────────────────────────────────────────
log "Installing Nginx site for ${DOMAIN}"
cp "${APP_DIR}/deploy/nginx-spd.conf" "${NGINX_SITE}"
ln -sf "${NGINX_SITE}" "${NGINX_LINK}"

# Disable the default welcome page if still enabled
if [[ -e /etc/nginx/sites-enabled/default ]]; then
    rm -f /etc/nginx/sites-enabled/default
fi

log "Testing Nginx config"
nginx -t
systemctl reload nginx

# ── 14. Done — next steps ────────────────────────────────────────────
cat <<EOF

────────────────────────────────────────────────────────────────────
  ✅  SPD Indonesia VPS bootstrap complete
────────────────────────────────────────────────────────────────────

  Frontend build  :  ${APP_DIR}/dist
  Backend (PM2)   :  pm2 logs spd-backend
  Backend .env    :  ${ENV_FILE}
  Nginx site      :  ${NGINX_SITE}

  NEXT STEPS — do these in order:

  1. Point DNS A records at this VPS:
        ${DOMAIN}        A    76.13.196.172
        ${WWW_DOMAIN}    A    76.13.196.172
     Verify with:  dig +short ${DOMAIN}

  2. Edit secrets in ${ENV_FILE}
     (SMTP creds at minimum — JWT_SECRET was auto-generated).
     Then:  pm2 restart spd-backend

  3. Issue TLS certificate (after DNS has propagated):
        sudo certbot --nginx -d ${DOMAIN} -d ${WWW_DOMAIN} \\
             --redirect --agree-tos -m admin@${DOMAIN} --no-eff-email
     Certbot will auto-renew via systemd timer.

  4. Seed initial admin (optional):
        cd ${BACKEND_DIR} && node seed.js

  5. Verify end-to-end:
        curl -I https://${DOMAIN}/
        curl -I https://${DOMAIN}/api/health   # if health route exists
        pm2 status
        systemctl status nginx

────────────────────────────────────────────────────────────────────
EOF
